package guestbook.pojo;
// Generated 06.05.2018 18:00:33 by Hibernate Tools 4.3.1



/**
 * Evaluierung generated by hbm2java
 */
public class Evaluierung  implements java.io.Serializable {


     private Integer id;
     private String kurs;
     private String lohntSich;
     private String platform;
     private String beibehalten;

    public Evaluierung() {
    }

    public Evaluierung(String kurs, String lohntSich, String platform, String beibehalten) {
       this.kurs = kurs;
       this.lohntSich = lohntSich;
       this.platform = platform;
       this.beibehalten = beibehalten;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getKurs() {
        return this.kurs;
    }
    
    public void setKurs(String kurs) {
        this.kurs = kurs;
    }
    public String getLohntSich() {
        return this.lohntSich;
    }
    
    public void setLohntSich(String lohntSich) {
        this.lohntSich = lohntSich;
    }
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    public String getBeibehalten() {
        return this.beibehalten;
    }
    
    public void setBeibehalten(String beibehalten) {
        this.beibehalten = beibehalten;
    }




}


